/* generated by wsdl2js.py (http://www.bolinfest.com/wsdl2js/) */

function Obj() {
   /*string*/ this["responseCode"] = null;
   /*string*/ this["responseText"] = null;
}

function cancelReservationHoldResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function ohostdataObj() {
   /*string*/ this["orgID"] = null;
   /*string*/ this["organizationName"] = null;
   /*Obj*/ this["sgData"] = null;
   /*int*/ this["sgID"] = null;
   /*string*/ this["sgName"] = null;
   /*string*/ this["parentGroupID"] = null;
}

function getStationGroupDetailsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function confirmReservationRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function updateFeedRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationResOpeningsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getCPNInstancesRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationloaddataObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["Address"] = null;
   /*int*/ this["shedState"] = null;
   /*string*/ this["stationLoad"] = null;
   /*string*/ this["allowedLoad"] = null;
   /*string*/ this["percentShed"] = null;
}

function getStationsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getReservableStationsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationSearchRequestExtendedObj() {
   /*string*/ this["orgID"] = null;
   /*string*/ this["organizationName"] = null;
   /*string*/ this["sgID"] = null;
   /*string*/ this["sgName"] = null;
}

function clearShedStateRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationRightsSearchRequestObj() {
   /*string*/ this["orgID"] = null;
   /*string*/ this["organizationName"] = null;
   /*string*/ this["sgID"] = null;
   /*string*/ this["sgName"] = null;
   /*Obj*/ this["provisionDateRange"] = null;
   /*date*/ this["startDate"] = null;
   /*date*/ this["endDate"] = null;
   /*string*/ this["currentFault"] = null;
   /*string*/ this["portStatus"] = null;
   /*string*/ this["adminStatus"] = null;
   /*string*/ this["networkStatus"] = null;
   /*string*/ this["provisionStatus"] = null;
}

function getOrgsAndStationGroupsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function groupsdataObj() {
   /*int*/ this["sgID"] = null;
   /*string*/ this["orgID"] = null;
   /*string*/ this["sgName"] = null;
   /*string*/ this["organizationName"] = null;
   /*Obj*/ this["stationData"] = null;
   /*string*/ this["stationID"] = null;
   /*geoDataObj*/ this["Geo"] = null;
}

function oStatusdataObj() {
   /*string*/ this["stationID"] = null;
   /*portDataStatusObj*/ this["Port"] = null;
}

function cancelReservationResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function serialNumberDataObj() {
   /*string*/ this["serialNumber"] = null;
}

function childGroupDataObj() {
   /*int*/ this["sgID"] = null;
   /*string*/ this["sgName"] = null;
}

function getPublicStationStatusRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function priceReservationResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function dataEventNameObj() {
   /*string*/ this["feedEventName"] = null;
}

function getStationsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationSearchRequestObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationManufacturer"] = null;
   /*string*/ this["stationModel"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["serialNumber"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*double*/ this["Proximity"] = null;
   /*string*/ this["proximityUnit"] = null;
   /*string*/ this["Connector"] = null;
   /*string*/ this["Voltage"] = null;
   /*string*/ this["Current"] = null;
   /*string*/ this["Power"] = null;
   /*serialNumberDataObj*/ this["demoSerialNumber"] = null;
   /*boolean*/ this["Reservable"] = null;
   /*geoDataObj*/ this["Geo"] = null;
   /*string*/ this["Level"] = null;
   /*string*/ this["Mode"] = null;
   /*pricingOptionsObj*/ this["Pricing"] = null;
}

function priceAndHoldReservationRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function oalarmsObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["stationModel"] = null;
   /*string*/ this["orgID"] = null;
   /*string*/ this["organizationName"] = null;
   /*string*/ this["stationManufacturer"] = null;
   /*string*/ this["stationSerialNum"] = null;
   /*int*/ this["portNumber"] = null;
   /*string*/ this["alarmType"] = null;
   /*dateTime*/ this["alarmTime"] = null;
}

function portDataStatusObj() {
   /*int*/ this["portNumber"] = null;
   /*string*/ this["Status"] = null;
   /*dateTime*/ this["TimeStamp"] = null;
   /*string*/ this["Connector"] = null;
   /*string*/ this["Power"] = null;
}

function stationDataRightsObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["stationSerialNum"] = null;
   /*string*/ this["stationMacAddr"] = null;
}

function shedLoadRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getChargePointCardsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function registerFeedsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function updateFeedResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function sessionSearchdataObj() {
   /*string*/ this["stationID"] = null;
   /*long*/ this["sessionID"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*double*/ this["Proximity"] = null;
   /*string*/ this["proximityUnit"] = null;
   /*dateTime*/ this["fromTimeStamp"] = null;
   /*dateTime*/ this["toTimeStamp"] = null;
   /*long*/ this["startRecord"] = null;
   /*geoDataObj*/ this["Geo"] = null;
}

function ocpninstancesObj() {
   /*string*/ this["cpnID"] = null;
   /*string*/ this["cpnName"] = null;
   /*string*/ this["cpnDescription"] = null;
}

function getStationGroupDetailsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationDataExtendedObj() {
   /*string*/ this["orgID"] = null;
   /*string*/ this["organizationName"] = null;
   /*string*/ this["sgID"] = null;
   /*string*/ this["sgName"] = null;
}

function shedLoadResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationGroupDataObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["Address"] = null;
}

function statusSearchdataObj() {
   /*string*/ this["stationID"] = null;
   /*stationIdListObj*/ this["stationIDs"] = null;
   /*string*/ this["stationManufacturer"] = null;
   /*string*/ this["stationModel"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*double*/ this["Proximity"] = null;
   /*string*/ this["proximityUnit"] = null;
   /*string*/ this["Connector"] = null;
   /*string*/ this["Voltage"] = null;
   /*string*/ this["Current"] = null;
   /*string*/ this["Power"] = null;
   /*boolean*/ this["portDetails"] = null;
   /*serialNumberDataObj*/ this["demoSerialNumber"] = null;
   /*boolean*/ this["Reservable"] = null;
   /*geoDataObj*/ this["Geo"] = null;
   /*int*/ this["Status"] = null;
   /*string*/ this["Level"] = null;
   /*string*/ this["Mode"] = null;
   /*pricingOptionsObj*/ this["Pricing"] = null;
}

function getReservationDetailsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationRightsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function rightsDataObj() {
   /*string*/ this["sgID"] = null;
   /*string*/ this["sgName"] = null;
   /*string*/ this["stationRightsProfile"] = null;
   /*stationDataRightsObj*/ this["stationData"] = null;
}

function getDriverReservationsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getPublicStationsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function pricingSpecificationObj() {
   /*string*/ this["Type"] = null;
   /*time*/ this["startTime"] = null;
   /*time*/ this["endTime"] = null;
   /*double*/ this["minPrice"] = null;
   /*double*/ this["maxPrice"] = null;
   /*int*/ this["initialUnitPriceDuration"] = null;
   /*double*/ this["unitPricePerHour"] = null;
   /*double*/ this["unitPricePerHourThereafter"] = null;
   /*double*/ this["unitPricePerSession"] = null;
   /*double*/ this["unitPricePerKWh"] = null;
   /*string*/ this["sessionTime"] = null;
}

function getPublicStationsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationDataObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationManufacturer"] = null;
   /*string*/ this["stationModel"] = null;
   /*string*/ this["stationMacAddr"] = null;
   /*string*/ this["stationSerialNum"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*portDataObj*/ this["Port"] = null;
   /*pricingSpecificationObj*/ this["Pricing"] = null;
   /*int*/ this["numPorts"] = null;
   /*string*/ this["mainPhone"] = null;
   /*dateTime*/ this["modTimeStamp"] = null;
   /*string*/ this["timezoneOffset"] = null;
   /*currencyCodeType*/ this["currencyCode"] = null;
}

function oresopeningsObj() {
   /*int*/ this["portNumber"] = null;
   /*string*/ this["startTime"] = null;
   /*string*/ this["endTime"] = null;
}

function getAlarmsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationRightsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getLoadResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function stationIdListObj() {
   /*string*/ this["stationID"] = null;
}

function getChargingSessionDataRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getLoadRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function ocarddataObj() {
   /*string*/ this["serialNumber"] = null;
   /*string*/ this["nickName"] = null;
}

function getPublicStationStatusResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationResOpeningsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationGroupsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getReservableStationsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function priceReservationRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getChargingSessionDataResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function registerFeedsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getOrgsAndStationGroupsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function sessionSearchResultdataObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationName"] = null;
   /*int*/ this["portNumber"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*long*/ this["sessionID"] = null;
   /*double*/ this["Energy"] = null;
   /*dateTime*/ this["startTime"] = null;
   /*dateTime*/ this["endTime"] = null;
   /*long*/ this["recordNumber"] = null;
   /*int*/ this["rfidSerialNumber"] = null;
   /*string*/ this["driverAccountNumber"] = null;
   /*string*/ this["driverName"] = null;
}

function getStationRightsProfileResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function confirmReservationResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function clearShedStateResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function cancelReservationHoldRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function clearAlarmsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function portDataObj() {
   /*int*/ this["portNumber"] = null;
   /*string*/ this["stationName"] = null;
   /*geoDataObj*/ this["Geo"] = null;
   /*string*/ this["Description"] = null;
   /*int*/ this["Reservable"] = null;
   /*string*/ this["Status"] = null;
   /*string*/ this["Level"] = null;
   /*dateTime*/ this["timeStamp"] = null;
   /*string*/ this["Mode"] = null;
   /*string*/ this["Connector"] = null;
   /*string*/ this["Voltage"] = null;
   /*string*/ this["Current"] = null;
   /*string*/ this["Power"] = null;
   /*double*/ this["estimatedCost"] = null;
}

function clearAlarmsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationRightsProfileRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function getStationGroupsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function get15minChargingSessionDataRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function feedStationSearchObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationModel"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*string*/ this["Level"] = null;
   /*boolean*/ this["Reservable"] = null;
   /*geoDataObj*/ this["Geo"] = null;
   /*int*/ this["Proximity"] = null;
   /*int*/ this["proximityUnit"] = null;
   /*string*/ this["Connector"] = null;
   /*string*/ this["Voltage"] = null;
   /*string*/ this["Current"] = null;
   /*string*/ this["Power"] = null;
   /*int*/ this["sgID"] = null;
}

function get15minChargingSessionDataResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getChargePointCardsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function oreservationdataObj() {
   /*string*/ this["serialNumber"] = null;
   /*string*/ this["reservationHandle"] = null;
   /*string*/ this["startTime"] = null;
   /*string*/ this["endTime"] = null;
   /*double*/ this["reservationPrice"] = null;
   /*currencyCodeType*/ this["currencyCode"] = null;
   /*int*/ this["portNumber"] = null;
}

function getReservationDetailsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function reservableStationSearchDataObj() {
   /*string*/ this["stationID"] = null;
   /*string*/ this["stationName"] = null;
   /*string*/ this["Address"] = null;
   /*string*/ this["City"] = null;
   /*string*/ this["State"] = null;
   /*string*/ this["Country"] = null;
   /*string*/ this["postalCode"] = null;
   /*double*/ this["Proximity"] = null;
   /*string*/ this["proximityUnit"] = null;
   /*serialNumberDataObj*/ this["demoSerialNumber"] = null;
   /*geoDataObj*/ this["Geo"] = null;
   /*string*/ this["Level"] = null;
   /*pricingOptionsObj*/ this["Pricing"] = null;
}

function geoDataObj() {
   /*string*/ this["Lat"] = null;
   /*string*/ this["Long"] = null;
}

function oChargingSessionsDataObj() {
   /*dateTime*/ this["stationTime"] = null;
   /*double*/ this["energyConsumed"] = null;
   /*double*/ this["peakPower"] = null;
   /*double*/ this["rollingPowerAvg"] = null;
}

function getCPNInstancesResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function cancelReservationRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

function priceAndHoldReservationResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function getDriverReservationsResponseObj() {
   /*Obj*/ this["parameters"] = null;
}

function pricingOptionsObj() {
   /*time*/ this["startTime"] = null;
   /*int*/ this["Duration"] = null;
   /*double*/ this["energyRequired"] = null;
   /*double*/ this["vehiclePower"] = null;
}

function getAlarmsRequestObj() {
   /*Obj*/ this["parameters"] = null;
}

/**
 * @param getPublicStationsRequest of type getPublicStationsRequestObj
 * @return getPublicStationsResponse
 */
function getPublicStations(getPublicStationsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getPublicStationsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getPublicStations", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getPublicStationsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getPublicStationsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getPublicStationStatusRequest of type getPublicStationStatusRequestObj
 * @return getPublicStationStatusResponse
 */
function getPublicStationStatus(getPublicStationStatusRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getPublicStationStatusRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getPublicStationStatus", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getPublicStationStatusResponseObj();
    var node0 = (translation.body.getElementsByTagName('getPublicStationStatusResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getReservableStationsRequest of type getReservableStationsRequestObj
 * @return getReservableStationsResponse
 */
function getReservableStations(getReservableStationsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getReservableStationsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getReservableStations", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getReservableStationsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getReservableStationsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getChargePointCardsRequest of type getChargePointCardsRequestObj
 * @return getChargePointCardsResponse
 */
function getChargePointCards(getChargePointCardsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getChargePointCardsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getChargePointCards", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getChargePointCardsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getChargePointCardsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param confirmReservationRequest of type confirmReservationRequestObj
 * @return confirmReservationResponse
 */
function confirmReservation(confirmReservationRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = confirmReservationRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "confirmReservation", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new confirmReservationResponseObj();
    var node0 = (translation.body.getElementsByTagName('confirmReservationResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param priceReservationRequest of type priceReservationRequestObj
 * @return priceReservationResponse
 */
function priceReservation(priceReservationRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = priceReservationRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "priceReservation", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new priceReservationResponseObj();
    var node0 = (translation.body.getElementsByTagName('priceReservationResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param priceAndHoldReservationRequest of type priceAndHoldReservationRequestObj
 * @return priceAndHoldReservationResponse
 */
function priceAndHoldReservation(priceAndHoldReservationRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = priceAndHoldReservationRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "priceAndHoldReservation", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new priceAndHoldReservationResponseObj();
    var node0 = (translation.body.getElementsByTagName('priceAndHoldReservationResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param cancelReservationRequest of type cancelReservationRequestObj
 * @return cancelReservationResponse
 */
function cancelReservation(cancelReservationRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = cancelReservationRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "cancelReservation", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new cancelReservationResponseObj();
    var node0 = (translation.body.getElementsByTagName('cancelReservationResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param cancelReservationHoldRequest of type cancelReservationHoldRequestObj
 * @return cancelReservationHoldResponse
 */
function cancelReservationHold(cancelReservationHoldRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = cancelReservationHoldRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "cancelReservationHold", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new cancelReservationHoldResponseObj();
    var node0 = (translation.body.getElementsByTagName('cancelReservationHoldResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getReservationDetailsRequest of type getReservationDetailsRequestObj
 * @return getReservationDetailsResponse
 */
function getReservationDetails(getReservationDetailsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getReservationDetailsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getReservationDetails", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getReservationDetailsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getReservationDetailsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getDriverReservationsRequest of type getDriverReservationsRequestObj
 * @return getDriverReservationsResponse
 */
function getDriverReservations(getDriverReservationsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getDriverReservationsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getDriverReservations", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getDriverReservationsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getDriverReservationsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getStationResOpeningsRequest of type getStationResOpeningsRequestObj
 * @return getStationResOpeningsResponse
 */
function getStationResOpenings(getStationResOpeningsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getStationResOpeningsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getStationResOpenings", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getStationResOpeningsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getStationResOpeningsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getAlarmsRequest of type getAlarmsRequestObj
 * @return getAlarmsResponse
 */
function getAlarms(getAlarmsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getAlarmsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getAlarms", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getAlarmsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getAlarmsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param clearAlarmsRequest of type clearAlarmsRequestObj
 * @return clearAlarmsResponse
 */
function clearAlarms(clearAlarmsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = clearAlarmsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "clearAlarms", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new clearAlarmsResponseObj();
    var node0 = (translation.body.getElementsByTagName('clearAlarmsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getOrgsAndStationGroupsRequest of type getOrgsAndStationGroupsRequestObj
 * @return getOrgsAndStationGroupsResponse
 */
function getOrgsAndStationGroups(getOrgsAndStationGroupsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getOrgsAndStationGroupsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getOrgsAndStationGroups", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getOrgsAndStationGroupsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getOrgsAndStationGroupsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param shedLoadRequest of type shedLoadRequestObj
 * @return shedLoadResponse
 */
function shedLoad(shedLoadRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = shedLoadRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "shedLoad", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new shedLoadResponseObj();
    var node0 = (translation.body.getElementsByTagName('shedLoadResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param clearShedStateRequest of type clearShedStateRequestObj
 * @return clearShedStateResponse
 */
function clearShedState(clearShedStateRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = clearShedStateRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "clearShedState", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new clearShedStateResponseObj();
    var node0 = (translation.body.getElementsByTagName('clearShedStateResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getLoadRequest of type getLoadRequestObj
 * @return getLoadResponse
 */
function getLoad(getLoadRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getLoadRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getLoad", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getLoadResponseObj();
    var node0 = (translation.body.getElementsByTagName('getLoadResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getStationGroupsRequest of type getStationGroupsRequestObj
 * @return getStationGroupsResponse
 */
function getStationGroups(getStationGroupsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getStationGroupsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getStationGroups", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getStationGroupsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getStationGroupsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getStationGroupDetailsRequest of type getStationGroupDetailsRequestObj
 * @return getStationGroupDetailsResponse
 */
function getStationGroupDetails(getStationGroupDetailsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getStationGroupDetailsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getStationGroupDetails", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getStationGroupDetailsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getStationGroupDetailsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getCPNInstancesRequest of type getCPNInstancesRequestObj
 * @return getCPNInstancesResponse
 */
function getCPNInstances(getCPNInstancesRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getCPNInstancesRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getCPNInstances", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getCPNInstancesResponseObj();
    var node0 = (translation.body.getElementsByTagName('getCPNInstancesResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getChargingSessionDataRequest of type getChargingSessionDataRequestObj
 * @return getChargingSessionDataResponse
 */
function getChargingSessionData(getChargingSessionDataRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getChargingSessionDataRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getChargingSessionData", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getChargingSessionDataResponseObj();
    var node0 = (translation.body.getElementsByTagName('getChargingSessionDataResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param get15minChargingSessionDataRequest of type get15minChargingSessionDataRequestObj
 * @return get15minChargingSessionDataResponse
 */
function get15minChargingSessionData(get15minChargingSessionDataRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = get15minChargingSessionDataRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "get15minChargingSessionData", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new get15minChargingSessionDataResponseObj();
    var node0 = (translation.body.getElementsByTagName('get15minChargingSessionDataResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getStationsRequest of type getStationsRequestObj
 * @return getStationsResponse
 */
function getStations(getStationsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getStationsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getStations", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getStationsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getStationsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getStationRightsRequest of type getStationRightsRequestObj
 * @return getStationRightsResponse
 */
function getStationRights(getStationRightsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getStationRightsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getStationRights", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getStationRightsResponseObj();
    var node0 = (translation.body.getElementsByTagName('getStationRightsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param getStationRightsProfileRequest of type getStationRightsProfileRequestObj
 * @return getStationRightsProfileResponse
 */
function getStationRightsProfile(getStationRightsProfileRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = getStationRightsProfileRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "getStationRightsProfile", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new getStationRightsProfileResponseObj();
    var node0 = (translation.body.getElementsByTagName('getStationRightsProfileResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param registerFeedsRequest of type registerFeedsRequestObj
 * @return registerFeedsResponse
 */
function registerFeeds(registerFeedsRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = registerFeedsRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "registerFeeds", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new registerFeedsResponseObj();
    var node0 = (translation.body.getElementsByTagName('registerFeedsResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

/**
 * @param updateFeedRequest of type updateFeedRequestObj
 * @return updateFeedResponse
 */
function updateFeed(updateFeedRequest) {
  var call = new window.SOAPCall();
  call.transportURI = "https://webservices.chargepoint.com/webservices/chargepoint/services/4.1";

  var param0 = new window.SOAPParameter();
  param0.name = "parameters";
  param0.value = updateFeedRequest["parameters"];

  var myParamArray = [param0];
  call.encode(0, "updateFeed", "", 0, null, myParamArray.length, myParamArray);
  var translation = call.invoke();

  if (translation.fault) {
    // error returned from the web service
    throw translation.fault;
  } else {
    var temp;
    var obj0 = new updateFeedResponseObj();
    var node0 = (translation.body.getElementsByTagName('updateFeedResponse'))[0];
    var obj1 = new Obj();
    var node1 = (node0.getElementsByTagName('parameters'))[0];
      temp = node1.getElementsByTagName('responseCode')[0].firstChild;
      obj1['responseCode'] = (temp == null) ? null : temp.nodeValue;
      temp = node1.getElementsByTagName('responseText')[0].firstChild;
      obj1['responseText'] = (temp == null) ? null : temp.nodeValue;
    obj0['parameters'] = obj1;
    return obj0['parameters'];
  }
}

